# Generated by Django 5.1.6 on 2025-03-23 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qube', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='group',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
